### ISSUE TITLE
Engine only plays first move from book

### ISSUE THREAD

**Issue by SamReeves** [ShailChoksi/lichess-bot#248]
I'm pretty certain this is not a bug... just an example of correct evaluation.

I want my bot to play some pretty bad openings and then "start playing chess".  However, it only selects the first move from the book, ie. d2d4 or e2e4.  Then it starts to play moves given from the evaluation.  Am I missing something?  Should I make a book with false valuations in it to trick into thinking that these bad variations are actually viable?

Thanks in advance!

**Comment by chessBOTneeder** [comment]
Does the bot book only have the first move, or somehow you created the book incorrectly?

**Comment by OIVAS7572** [comment]
what is your "min_weight"?
try reducing that
use some big books
this link sometimes help you
https://www.chess2u.com/f4-computer-chess-opening-books

**Comment by MarkZH** [comment]
@SamReeves Do you still need help with this issue?

**Comment by SamReeves** [comment]
I stopped trying to figure this out ages ago... But, I could definitely go back to it.

**Comment by MarkZH** [comment]
After doing some reading, it looks like what you want to do is create a `polyglot` section in your bot's `config.yml` with the following configurations:
```yml
polyglot:
  enabled: true
  book:
    # list books here
  min_weight: 0 # choose from all legal moves
  selection: "uniform_random" # choose a move with equal probability, regardless of quality
  max_depth: 2 # or however many bad moves to make before starting to play for real
```
This will essentially pick a random legal move from the first few positions in the game. These will probably be bad moves since moving randomly is rarely a good strategy. If you only want to pick bad moves, you'll either have to create your own polyglot books with good moves getting low weights, or write a polyglot parser into your bot that chooses low weight moves. [Here's a link](http://hgm.nubati.net/book_format.html) to the polyglot book format, in case it might be useful.
