### ISSUE TITLE
why arent Skill_level and multi_pv in the config.yml.default file?

### ISSUE THREAD

**Issue by vibranium21** [ShailChoksi/lichess-bot#331]
title explains

**Comment by skibur** [comment]
I was going to ask the same thing.

**Comment by MarkZH** [comment]
Different engines have different options. The configurations in config.yml.default are examples to show how options should be specified. You are free to add, remove, or change any option in your own config.yml.

**Comment by skibur** [comment]
How would I add Skill Level for Stockfish?

engine
  dir: "./engines/"          # dir containing engines, relative to this project.
  name: "stockfish.exe"        # Binary name of the engine to use.
  **skill_level: "1"**
  protocol: "uci"            # "uci" or "xboard"

**Comment by MarkZH** [comment]
Place it under the `uci_options:` section in `config.yml`. Like this:

```yml
engine:                      # Engine settings.
  dir: "./engines/"          # dir containing engines, relative to this project.
  name: "stockfish.exe"      # Binary name of the engine to use.
  protocol: "uci"            # "uci" or "xboard"
  ponder: true               # Think on opponent's time.
  uci_options:               # Arbitrary UCI options passed to the engine.
    Move Overhead: 100       # Increase if your bot flags games too often.
    Threads: 2               # Max CPU threads the engine can use.
    Hash: 256
    Skill Level: 1 # <-- Add here
```
If you run Stockfish on the command line and type `uci` after it starts up, it will print a list of options that can be configured here. Here's what I see after installing Stockfish:

```
Stockfish 13 by the Stockfish developers (see AUTHORS file)
uci # <-- I typed this
id name Stockfish 13
id author the Stockfish developers (see AUTHORS file)

option name Debug Log File type string default 
option name Contempt type spin default 24 min -100 max 100
option name Analysis Contempt type combo default Both var Off var White var Black var Both
option name Threads type spin default 1 min 1 max 512
option name Hash type spin default 16 min 1 max 33554432
option name Clear Hash type button
option name Ponder type check default false
option name MultiPV type spin default 1 min 1 max 500
option name Skill Level type spin default 20 min 0 max 20
option name Move Overhead type spin default 10 min 0 max 5000
option name Slow Mover type spin default 100 min 10 max 1000
option name nodestime type spin default 0 min 0 max 10000
option name UCI_Chess960 type check default false
option name UCI_AnalyseMode type check default false
option name UCI_LimitStrength type check default false
option name UCI_Elo type spin default 1350 min 1350 max 2850
option name UCI_ShowWDL type check default false
option name SyzygyPath type string default <empty>
option name SyzygyProbeDepth type spin default 1 min 1 max 100
option name Syzygy50MoveRule type check default true
option name SyzygyProbeLimit type spin default 7 min 0 max 7
option name Use NNUE type check default true
option name EvalFile type string default nn-62ef826d1a6d.nnue
uciok
```
Anything you see after `option name` can be a configuration put in the `uci_options:` section for configuration. There are a few exceptions ("uci_chess960", "uci_variant", "multipv", "ponder") that will be ignored because they are handled internally (it makes no sense to set "uci_chess960" to "true" until an actual Chess960 game starts). I notice that it is "Skill Level" instead of "Skill_Level" with an underscore. So you might want to check that if you see an error when starting a game on lichess-bot.
