### ISSUE TITLE
welcoing messages

### ISSUE THREAD

**Issue by barca-cloud2010** [ShailChoksi/lichess-bot#373]
when the bots play the game at start  there shoyuld be welcoming messages like hello good luck
and at end of game good game!

**Comment by barca-cloud2010** [comment]
anyone tell me pls ?

**Comment by MarkZH** [comment]
Please try the pull request and let me know if it works for you. You will have to add the following to the end of your `config.yml`:

```yml
greeting:
    hello: Hello! Good luck!
    goodbye: Good game!
```
You can modify the messages how you want.
