### ISSUE TITLE
Feature Request: Implement matchmaking

### ISSUE THREAD

**Issue by TheYoBots** [ShailChoksi/lichess-bot#472]
To randomly challenge other lichess **bots** (not extended to human accounts) at a set interval, time control and rating. Similar to what has been implemented here: https://github.com/Torom/BotLi

Maybe an option in the config.yml having something like:
```yml
matchmaking:
  allow_matchmaking: false    # Set it to 'true' to challenge other bot in a set interval, time control and range.
  challenge_interval: 30      # Interval in minutes between two challenges.
  challenge_initial_time: 60  # Initial time in seconds of the challenge.
  challenge_increment: 3      # Increment in seconds of the challenge.
  opponent_min_rating: 2500   # Opponents rating should be above this value
  opponent_max_rating: 2900   # Opponents rating should be below this value
  challenge_mode: random      # Set it to the mode in which challenges are sent. Possible options are 'casual', 'rated' and 'random'.  # This might be tricky?
```

I think many lichess bot users have taken interest in this feature. Extending this feature here would be great!
