### ISSUE TITLE
Go-commands doesn't function properly.

### ISSUE THREAD

**Issue by TheBlackPlague** [ShailChoksi/lichess-bot#480]
I have my `go-commands` defined like so:
```
  go_commands:             # Additional options to pass to the UCI go command.
  #     nodes: 1               # Search so many nodes only.
  #     depth: 5               # Search depth ply only.
      movetime: 3500         # Integer. Search exactly movetime milliseconds.
```

However, this doesn't work apparently and the script still always sends:
```
2022-06-02 10:45:03,336: <UciProtocol (pid=8784)>: << go wtime 300520 btime 299350 winc 3000 binc 3000
```

Is there a way to only request the specified go-command to be sent?

**Comment by AttackingOrDefending** [comment]
From the small part of your config.yml that you posted it seems that `go_commands` is on the save level as `uci_options` and not indented.
The structure of your config.yml file, should be something like:
```yml
engine:
  ...
  uci_options:               # Arbitrary UCI options passed to the engine.
    Threads: 2               # Max CPU threads the engine can use.
    Hash: 256                # Max memory (in megabytes) the engine can allocate.
    go_commands:             # Additional options to pass to the UCI go command.
#     nodes: 1               # Search so many nodes only.
#     depth: 5               # Search depth ply only.
      movetime: 3500         # Integer. Search exactly movetime milliseconds.
```
The command `wtime`, `btime`, `winc` and `binc ` will always be sent, with the `go_commands` added at the end. For example:
```
2022-06-02 10:00:00,000: <UciProtocol (pid=9460)>: << go wtime 68644 btime 71200 winc 2000 binc 2000 movetime 3500
```
If this doesn't work, post your config.yml with your token removed.
