### ISSUE TITLE
engine error

### ISSUE THREAD

**Issue by thechipsss** [ShailChoksi/lichess-bot#496]
sorry for agin creating a post i need some help as it shows engine error 
 --- Process Used. Total Queued: 0. Total Used: 1                        lichess-bot.py:199
[07/09/22 21:07:34] INFO     Backing off create_engine(...) for 0.9s (OSError: [WinError 193] %1 is not  _common.py:105
                             a valid Win32 application)
[07/09/22 21:07:35] INFO     Backing off create_engine(...) for 1.9s (OSError: [WinError 193] %1 is not  _common.py:105
                             a valid Win32 application)
[07/09/22 21:07:36] INFO     Backing off create_engine(...) for 0.8s (OSError: [WinError 193] %1 is not  _common.py:105
                             a valid Win32 application)
[07/09/22 21:07:37] INFO     Backing off create_engine(...) for 0.3s (OSError: [WinError 193] %1 is not  _common.py:105
                             a valid Win32 application)
[07/09/22 21:07:38] INFO     Backing off create_engine(...) for 8.4s (OSError: [WinError 193] %1 is not  _common.py:105
                             a valid Win32 application)
[07/09/22 21:07:46] INFO     Backing off create_engine(...) for 17.3s (OSError: [WinError 193] %1 is not _common.py:105
                             a valid Win32 application)

**Comment by AttackingOrDefending** [comment]
In the `name` field in config.yml, you have a file named `not _common.py`. A python file isn't a valid Win32 application. You can convert your python file to exe if you have made an engine in python and want to use it. An engine isusually an exe file, so you can try changing your `config.yml` from:
```yml
url: "https://lichess.org/"  # Lichess base URL.

engine:                      # Engine settings.
  dir: "./engines/"          # Directory containing engines, relative to this project.
  name: "not _common.py"       # Binary name of the engine to use.
  ...
```
to 
```yml
url: "https://lichess.org/"  # Lichess base URL.

engine:                      # Engine settings.
  dir: "./engines/"          # Directory containing engines, relative to this project.
  name: "engine.exe"       # Binary name of the engine to use.
  ...
```
