### ISSUE TITLE
How

### ISSUE THREAD

**Issue by FatFritz2** [ShailChoksi/lichess-bot#545]
I am wondering how to make Stockfish move faster (In the UCI_Options) (Trying to make it move like 1 move per second, immediately, i mean)
I still dont know how to enable matchmaking mode :C pls help

**Comment by MarkZH** [comment]
In your config.yml, you can add specific options for UCI engines in the following sections (see [lines 73-80 in config.yml.default](https://github.com/ShailChoksi/lichess-bot/blob/986802928829781c9d4d2887ed3d465fd9a8223f/config.yml.default#L73))
```yml
uci_options:               # Arbitrary UCI options passed to the engine.
  go_commands:             # Additional options to pass to the UCI go command.
    movetime: 1000         # Integer. Search exactly movetime milliseconds.
```
This configuration will set Stockfish to think for 1000 ms (1 second) for each move, regardless of clock time.

To enable matchmaking mode, see the [matchmaking section of config.yml.default starting on line 147](https://github.com/ShailChoksi/lichess-bot/blob/986802928829781c9d4d2887ed3d465fd9a8223f/config.yml.default#L147). Set `allow_matchmaking:` to `true` and change the matchmaking parameters to your liking.

Let us know if you need more help.
