### ISSUE TITLE
Matchmaking issue

### ISSUE THREAD

**Issue by FatFritz2** [ShailChoksi/lichess-bot#556]
Hey, I want to make my bot auto challenge other bots with 10 + 0 time control 
Ye so can you help ? 
Thanks :D

**Comment by MarkZH** [comment]
I'm assuming you mean 10-minute games with no increment. Bots aren't allowed to play 10-second or other ultrabullet time controls. In your config.yml file, use these settings:
```yaml
matchmaking:
  allow_matchmaking: true
  challenge_initial_time:     # Initial time in seconds of the challenge (to be chosen at random).
    - 600
  challenge_increment:        # Increment in seconds of the challenge (to be chosen at random).
    - 0
```
See the README page and config.yml.default for more options.
